In [1]:
import cv2
import numpy as np
from keras.models import load_model

In [4]:

# Pfade zum Gesichtserkennungsmodell und zu den Kaskadendateien
model_path = 'models\ResNet101_model.h5'
face_cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'

# Gesichtserkennungsmodell laden
model = load_model(model_path)

# Kaskade für die Gesichtserkennung erstellen
face_cascade = cv2.CascadeClassifier(face_cascade_path)

# Funktion zum Erkennen von Gesichtern
def detect_faces(image):
    rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    faces = face_cascade.detectMultiScale(rgb, 1.3, 5)
    return faces

# Webcam initialisieren
cap = cv2.VideoCapture(0)

# Endlosschleife für die Gesichtserkennung
while True:
    # Bild von der Webcam erfassen
    ret, frame = cap.read()

    # Gesichter erkennen
    faces = detect_faces(frame)

    # Für jedes erkannte Gesicht Vorhersage treffen
    for (x, y, w, h) in faces:
        face_image = frame[y:y+h, x:x+w]
        face_image = cv2.resize(face_image, (224, 224))
        face_image = np.expand_dims(face_image, axis=0)
        img_norm = cv2.normalize(face_image, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
        face_image = img_norm

        # Gesichtsklassifizierung durchführen
        predictions = model.predict(face_image)
        print(predictions)
        # Ergebnisse anzeigen
        if predictions[0][0] > 0.4:
            label = 'Dominik'
        else:
            label = 'Unknown'

        
        # predicted_label = predictions[0][0] > 0.5
        # myFace = ('Dominik', 'Unknown')
        # label = myFace[predicted_label]

        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

    # Bild anzeigen
    cv2.imshow('Gesichtserkennung', frame)

    # Beenden der Schleife bei Drücken der Taste 'q'
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Webcam-Stream beenden
cap.release()
cv2.destroyAllWindows()


[[0.5961483 0.4038517]]
[[0.24748643 0.7525135 ]]
[[0.20441192 0.79558814]]
[[0.31802282 0.6819772 ]]
[[0.29291055 0.7070894 ]]
[[0.25142384 0.74857616]]
[[0.39907476 0.6009252 ]]
[[0.22430556 0.77569443]]
[[0.27718094 0.72281903]]
[[0.3042769 0.6957231]]
[[0.23539814 0.7646018 ]]
[[0.24440655 0.7555935 ]]
[[0.36207736 0.63792264]]
[[0.25423414 0.74576586]]
[[0.15532373 0.84467626]]
[[0.16295248 0.8370475 ]]
[[0.19227822 0.80772185]]
[[0.16562542 0.8343746 ]]
[[0.2498851 0.7501149]]
[[0.23238072 0.7676193 ]]
[[0.3365122  0.66348785]]
[[0.15653428 0.8434657 ]]
[[0.17005013 0.82994986]]
[[0.33221376 0.66778624]]
[[0.17369883 0.82630116]]
[[0.23812474 0.7618753 ]]
[[0.16065493 0.8393451 ]]
[[0.24121797 0.758782  ]]
[[0.28472856 0.7152715 ]]
[[0.16257493 0.83742505]]
[[0.36875662 0.63124335]]
[[0.23111083 0.7688892 ]]
[[0.22641043 0.77358955]]
[[0.17960621 0.82039374]]
[[0.17288385 0.8271162 ]]
[[0.24215601 0.757844  ]]
[[0.19285853 0.8071415 ]]
[[0.20797276 0.7920273 ]]
[[0.24552643 0.754