In [1]:
import cv2
import numpy as np
from keras.models import load_model

In [7]:

# Pfade zum Gesichtserkennungsmodell und zu den Kaskadendateien
model_path = 'models\InceptionV3_model.h5'
face_cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'

# Gesichtserkennungsmodell laden
model = load_model(model_path)

# Kaskade für die Gesichtserkennung erstellen
face_cascade = cv2.CascadeClassifier(face_cascade_path)

# Funktion zum Erkennen von Gesichtern
def detect_faces(image):
    rgb = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(rgb, 1.3, 5)
    return faces

# Webcam initialisieren
cap = cv2.VideoCapture(0)

# Endlosschleife für die Gesichtserkennung
while True:
    # Bild von der Webcam erfassen
    ret, frame = cap.read()

    # Gesichter erkennen
    faces = detect_faces(frame)

    # Für jedes erkannte Gesicht Vorhersage treffen
    for (x, y, w, h) in faces:
        face_image = frame[y:y+h, x:x+w]
        face_image = cv2.resize(face_image, (224, 224))
        face_image = np.expand_dims(face_image, axis=0)
        img_norm = cv2.normalize(face_image, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
        face_image = img_norm

        # Gesichtsklassifizierung durchführen
        predictions = model.predict(face_image)
        print(predictions)
        # Ergebnisse anzeigen
        if predictions[0][0] > 0.7:
            label = 'Dominik'
        else:
            label = 'Unknown'

        
        # predicted_label = predictions[0][0] > 0.5
        # myFace = ('Dominik', 'Unknown')
        # label = myFace[predicted_label]

        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

    # Bild anzeigen
    cv2.imshow('Gesichtserkennung', frame)

    # Beenden der Schleife bei Drücken der Taste 'q'
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Webcam-Stream beenden
cap.release()
cv2.destroyAllWindows()


[[0.06214705 0.937853  ]]
[[0.06316146 0.93683857]]
[[0.06315215 0.93684787]]
[[0.06317378 0.9368262 ]]
[[0.06312524 0.93687475]]
[[0.06343372 0.9365663 ]]
[[0.0633027  0.93669736]]
[[0.06313431 0.9368657 ]]
[[0.06313778 0.93686223]]
[[0.06319754 0.93680245]]
[[0.06349903 0.93650097]]
[[0.06327361 0.9367264 ]]
[[0.06340648 0.9365935 ]]
[[0.06357157 0.9364284 ]]
[[0.06389759 0.9361024 ]]
[[0.06405283 0.9359472 ]]
[[0.06323498 0.936765  ]]
[[0.0633807  0.93661934]]
[[0.06390967 0.93609035]]
[[0.06369216 0.9363079 ]]
[[0.06335746 0.9366425 ]]
[[0.06382645 0.9361735 ]]
[[0.06318117 0.9368188 ]]
[[0.06317529 0.93682474]]
[[0.06338746 0.93661255]]
[[0.06321757 0.9367825 ]]
[[0.06347571 0.9365243 ]]
[[0.06370103 0.936299  ]]
[[0.06341562 0.9365844 ]]
[[0.06361156 0.9363885 ]]
[[0.0634051  0.93659484]]
[[0.06404551 0.93595445]]
[[0.06396309 0.9360369 ]]
[[0.06415085 0.93584913]]
[[0.06390804 0.9360919 ]]
[[0.06388237 0.9361176 ]]
[[0.06243178 0.93756825]]
[[0.06338109 0.9366189 ]]
[[0.06362442