In [1]:
import cv2
import numpy as np
from keras.models import load_model
from PIL import Image
from keras.preprocessing.image import img_to_array, array_to_img

In [10]:

# Pfade zum Gesichtserkennungsmodell und zu den Kaskadendateien
model_path = 'ResNet50_model.h5'
face_cascade_path = cv2.data.haarcascades + 'haarcascade_frontalface_default.xml'

# Gesichtserkennungsmodell laden
model = load_model(model_path)

# Kaskade für die Gesichtserkennung erstellen
face_cascade = cv2.CascadeClassifier(face_cascade_path)

# Funktion zum Erkennen von Gesichtern
def detect_faces(image):
    rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    faces = face_cascade.detectMultiScale(rgb, 1.3, 5)
    return faces

# Webcam initialisieren
cap = cv2.VideoCapture(0)

# Endlosschleife für die Gesichtserkennung
while True:
    # Bild von der Webcam erfassen
    ret, frame = cap.read()

    # Gesichter erkennen
    faces = detect_faces(frame)

    # Für jedes erkannte Gesicht Vorhersage treffen
    for (x, y, w, h) in faces:
        face_image = frame[y:y+h, x:x+w]
        
        #face_image = np.expand_dims(face_image, axis=0)
        face_image = cv2.normalize(face_image, None, alpha=0, beta=1, norm_type=cv2.NORM_MINMAX, dtype=cv2.CV_32F)
        face_image = array_to_img(face_image)
        face_image = face_image.resize((224, 224))
        face_image = np.expand_dims(face_image, axis=0)
        face_image = np.array(face_image)

        # Gesichtsklassifizierung durchführen
        predictions = model.predict(face_image)
        print(predictions)
        # Ergebnisse anzeigen
        if predictions[0][0] > 0.6:
            label = 'Dominik'
        else:
            label = 'Unknown'

        
        # predicted_label = predictions[0][0] > 0.5
        # myFace = ('Dominik', 'Unknown')
        # label = myFace[predicted_label]

        cv2.rectangle(frame, (x, y), (x+w, y+h), (0, 255, 0), 2)
        cv2.putText(frame, label, (x, y-10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (0, 255, 0), 2)

    # Bild anzeigen
    cv2.imshow('Gesichtserkennung', frame)

    # Beenden der Schleife bei Drücken der Taste 'q'
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Webcam-Stream beenden
cap.release()
cv2.destroyAllWindows()


[[0.06107367 0.9389263 ]]
[[0.5738709  0.42612916]]
[[0.6823199 0.3176801]]
[[0.5664836  0.43351638]]
[[0.5046593  0.49534073]]
[[0.47593325 0.5240668 ]]
[[0.5936592 0.4063408]]
[[0.6243648  0.37563527]]
[[0.77446896 0.22553098]]
[[0.66733706 0.332663  ]]
[[0.4871678  0.51283216]]
[[0.62365943 0.37634057]]
[[0.52900076 0.4709993 ]]
[[0.5806342  0.41936585]]
[[0.5295467 0.4704533]]
[[0.49730173 0.50269824]]
[[0.6145215  0.38547856]]
[[0.5194317  0.48056832]]
[[0.65174496 0.34825504]]
[[0.46230248 0.5376975 ]]
[[0.5839063 0.4160937]]
[[0.7101236  0.28987643]]
[[0.730044 0.269956]]
[[0.71792257 0.28207746]]
[[0.5575332 0.4424668]]
[[0.81533676 0.1846632 ]]
[[0.8187702  0.18122984]]
[[0.68318224 0.3168178 ]]
[[0.7652192  0.23478076]]
[[0.63389975 0.36610028]]
[[0.5344522  0.46554777]]
[[0.49486724 0.5051328 ]]
[[0.63526124 0.36473876]]
[[0.6219645 0.3780355]]
[[0.71651906 0.28348097]]
[[0.5281335 0.4718665]]
[[0.4778936  0.52210635]]
[[0.808736   0.19126399]]
[[0.5808772 0.4191228]]
[[0.57